### ISSUE TITLE
Panel field not working as expected

### ISSUE THREAD

**Issue by oliverwendenburg** [dweidner/kirby-firewall#5]
I cannot get the panel field to work as expected (and shown in the gif). I even tried it on an empty Kirby 2.4.1 StarterKit with nothing but the module installed and used on the homepage. It saves everything correctly but the show/hide thing seems not to work even though the browser doesn't throw any javascript errors.

Thank you for your work, I will of course use the field.

**Comment by dweidner** [comment]
That is strange. I am currently using the plugin on one of my sites. I will create a test site and investigate your issue further. Thank you for your feedback.

**Comment by dweidner** [comment]
Sorry, I introduced some issues when I was renaming the field. Issue should be solved now.

**Comment by oliverwendenburg** [comment]
No problem, I'm happy you are developing and supporting the module.
